Guce.MvcWebUI/Models/Form/FindListViewModel.cs
using Guce.Entities.ComplexType;
using Guce.Entities.Concrete;

namespace Guce.MvcWebUI.Models.Form
{
    public class FindListViewModel
    {
        public WfAction Action { get; set; }
        public int ActionId { get; set; }
        public int EntityId { get; set; }
        public int FlowId { get; set; }
        public int WflId { get; set; }
        public int WfvId { get; set; }
        public string Keyword { get; set; }
        public string Entities { get; set; }
        public VwUserNextAction VwUserNextAction { get; set; }
    }
}

Guce.MvcWebUI/Models/Form/FormListViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Guce.Entities.ComplexType;
using Guce.Entities.Concrete;
using Guce.MvcWebUI.Models.Custom;

namespace Guce.MvcWebUI.Models.Form
{
    public class FormListViewModel
    {
        public WfAction Action { get; set; }
        public int ActionId { get; set; }
        public int WflId { get; set; }
        public int WfvId { get; set; }
        public int FlowId { get; set; }
        public int EntityId { get; set; }
        public int StatusId { get; set; }
        public string Reference { get; set; }
        public VwUserNextAction VwUserNextAction { get; set; }
        public List<IGrouping<string, VwFormField>> FormFields { get; set; }
        public List<ComponentInfo> Infos { get; set; }
    }
}

Guce.MvcWebUI/Models/Form/PrintListViewModel.cs
using Guce.Entities.ComplexType;
using Guce.Entities.Concrete;

namespace Guce.MvcWebUI.Models.Form
{
    public class PrintListViewModel
    {
        public int WflId { get; set; }
        public WfAction Action { get; set; }
        public int ActionId { get; set; }
        public int WfvId { get; set; }
        public int FlowId { get; set; }
        public int EntityId { get; set; }
        public int StatusId { get; set; }
        public string Reference { get; set; }
        public VwUserNextAction VwUserNextAction { get; set; }
        public int ReportId { get; set; }
        public string FunctionToPrint { get; set; }
        public object DocumentToPrint { get; set; }
    }
}

Guce.MvcWebUI/Models/Form/ReferenceListViewModel.cs
using System.Collections.Generic;
using Guce.Entities.Concrete;
using Guce.MvcWebUI.Models.Custom;

namespace Guce.MvcWebUI.Models.Form
{
    public class ReferenceListViewModel
    {
        public string IdParent { get; set; }
        public int DicId { get; set; }
        public List<Value> Values { get; set; }
        public List<ComponentInfo> Infos { get; set; }
    }
}

Guce.MvcWebUI/Models/Form/TempDataInfo.cs
namespace Guce.MvcWebUI.Models.Form
{
    public class TempDataInfo
    {

    }
}

Guce.MvcWebUI/Controllers/LoginController.cs
/*=================================================================*
 * Classe: <LoginController>
 * Version/date: <2.0.0> <2016.07.09>
 *
 * Description: <” Cette classe est le controleur pour la page d'authentification (connexion). ”>
 * Specificities: <“ Cette classe est un controller. ”>
 *
 * Authors:   <Steve> <DILU>
 * Copyright: GUCE/ESSOR, all rights reserved
 *
 *================================================================*/

using System;
using System.Linq;
using System.Web.Mvc;
using Guce.Business.Abstract;
using Guce.DataAccess.Concrete;
using Guce.DataAccess.Concrete.Context;
using Guce.Entities.Custom;
using Guce.MvcWebUI.Models.Login;

namespace Guce.MvcWebUI.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserGroupService _userGroupService;
        private readonly IParameterService _parameterService;
        private readonly IStatPageService _statPageService;
        private readonly IUserService _userService;

        public LoginController(IUserGroupService userGroupService, IParameterService parameterService, 
            IUserService userService, IStatPageService statPageService)
        {
            _userGroupService = userGroupService;
            _parameterService = parameterService;
            _userService = userService;
            _statPageService = statPageService;
        }

        public ActionResult Index()
        {
            var user = new User
            {
                Authentifie = HttpContext.User.Identity.IsAuthenticated
            };

            if (HttpContext.User.Identity.IsAuthenticated)
            {
                //return Redirect("Home");
            }
            return View(new LoginViewModel
            {
                User = user
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(User user, string returnUrl)
        {
            if (!ModelState.IsValid) return View(new LoginViewModel
            {
                User = user
            });
            Session["username"] = user.Username;
            Session["password"] = user.Password;
            
            if (GuceContextConnexion.TestContext(user.Username, user.Password))
            {
                Configuration.Parameters.Clear();
                var parameters = _parameterService.GetParameters(ParameterId.App, user.Username);
                foreach (var par in parameters.Where(par => !Configuration.Parameters.Contains(par.Id)))
                {
                    if (par.Username.Equals(ParameterId.App))
                    {
                        Configuration.Parameters.Add(par.Id, par.Value);
                    }
                    else
                    {
                        Session[par.Id + "_" + par.Username] = par.Value;
                    }
                }
                Session["isAdmin"] = EfDatabaseFunction.IsAdmin();
                var groups = (bool)Session["isAdmin"] ? _userGroupService.Roles(user.Username) : _userGroupService.Groups(user.Username);
                Session["userGroup"] = groups;
                user.UserGroup = groups;

                var stat = _statPageService.GetStatPages().FirstOrDefault();
                if (stat != null)
                {
                    Session["statPage"] = _userGroupService.InGroup(stat.GrpId, user.Username);
                }
                else
                {
                    Session["statPage"] = false;
                }

                Session["fullname"] = !(bool)Session["isAdmin"] ? _userService.GetUser(user.Username).Fullname : user.Username;
                
                GuceContextSession.CreateCookies(user);
                if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl)) return Redirect(returnUrl);
                return Redirect("~/Home");
            }
            TempData.Add("Message", "Vos paramètres de connexion sont incorrects");
            return View(new LoginViewModel
            {
                User = user
            });
        }
        
        public ActionResult Logout()
        {
            var username = GuceContextSession.ReadCookie().Username;
            var keys = System.Web.HttpContext.Current.Application.AllKeys;
            foreach (var k in keys.Where(k => System.Web.HttpContext.Current.Application[k] != null 
                                              && System.Web.HttpContext.Current.Application[k].ToString().Equals(username)))
            {
                System.Web.HttpContext.Current.Application[k] = null;
            }
            GuceContextSession.DestroyCookies();
            return Redirect("~/Login");
        }

        [HttpPost]
        public string TimeOut()
        {
            //var username = GuceContextSession.ReadCookie().Username;
            var parameters = _parameterService.GetParameters().FirstOrDefault(e => e.Id == "SESSION_TIMEOUT");
            if (parameters == null) throw new ArgumentNullException(nameof(parameters));
            return parameters.Value;
        }
    }
}

Guce.MvcWebUI/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Guce.Business.Abstract;
using Guce.DataAccess.Concrete;
using Guce.Entities.Custom;
using Guce.MvcWebUI.CustomClass;

namespace Guce.MvcWebUI.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {

        private readonly IReportService _reportService;
        private readonly IUserService _userService;
        private readonly IDicFieldService _dicFieldService;
        private readonly IVwCurrentValueService _vwCurrentValueService;
        private readonly IVwLastValidatedValuesService _vwLastValidatedValuesService;

        public ReportController(IReportService reportService, IUserService userService,
             IVwLastValidatedValuesService vwLastValidatedValuesService, 
             IVwCurrentValueService vwCurrentValueService, IDicFieldService dicFieldService)
        {
            _reportService = reportService;
            _userService = userService;
            _vwLastValidatedValuesService = vwLastValidatedValuesService;
            _vwCurrentValueService = vwCurrentValueService;
            _dicFieldService = dicFieldService;
        }

        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string GetFieldProperties()
        {
            return new JavaScriptSerializer().Serialize(_dicFieldService.GetFieldProperties());
        }

        [HttpPost]
        public string FindInfoToPrint(int reportId)
        {
            var report = EfDatabaseFunction.fun_generate_variables_json(reportId).ToList().FirstOrDefault();// _reportService.GetReports().Where(e => e.Id == reportId).ToList().FirstOrDefault();

            if (report != null) return report;
            return "";
        }

        [HttpPost]
        public string FindNumeroDossier(int entityId)
        {
            var report = EfDatabaseFunction.fun_generate_variables_json(entityId).FirstOrDefault();// _reportService.GetReports().Where(e => e.Id == reportId).ToList().FirstOrDefault();

            if (report != null) return report;
            return "";
        }

        [HttpPost]
        public string FindInfoNotaire(int entityId)
        {
            string currentUser = (string)Session["username"];
            var report = EfDatabaseFunction.fun_generate_not_validated_json(entityId, currentUser,
                EfDatabaseFunction.FunGenerateNotValidatedJsonPropertie.All).FirstOrDefault();// _reportService.GetReports().Where(e => e.Id == reportId).ToList().FirstOrDefault();

            if (report != null) return report;
            return "";
        }

        [HttpPost]
        public string FindMoreInfoNotaire(int entityId)
        {
            string json = null;
            string currentUser = (string)Session["username"];
            var result = _userService.GetUsers().FirstOrDefault(e => e.Username == currentUser);
            //var report = DataAccess.Concrete.EfDatabaseFunction.FindInfoNotaire(entityId,currentUser).FirstOrDefault();// _reportService.GetReports().Where(e => e.Id == reportId).ToList().FirstOrDefault();

            if (result != null)
            {
                json = new JavaScriptSerializer().Serialize(result.Attributes);

                return json;
            }
            return json;
        }

        [HttpPost]
        public string FindFluxValues(int entityId, int flowId)
        {
            string json = null;
            string currentUser = (string)Session["username"];
            //var result = _userService.GetUsers().FirstOrDefault(e => e.Username == currentUser);
            var result = EfDatabaseFunction.FindFluxValues(entityId, flowId, currentUser);// _reportService.GetReports().Where(e => e.Id == reportId).ToList().FirstOrDefault();

            if (result != null)
            {
                json = new JavaScriptSerializer().Serialize(result);

                return json;
            }
            return json;
        }

        [HttpPost]
        public string GetValueModified(int entityId, int txId)
        {
            string json = null;
            var result = new List<ModifiedValues>();
            try
            {
                var newValue = _vwCurrentValueService.GetCurrentValues(entityId).Where(e => e.TxId == txId).ToList();
                var lastValue = _vwLastValidatedValuesService.GetLastValidatedValues(entityId);
                
                for (int i = 0; i < newValue.Count; i++)
                {
                    var vwCurrent = lastValue.FirstOrDefault(e => e.ent_id == newValue[i].EntId && e.dfl_id == newValue[i].DflId);
                    if (vwCurrent == null)
                    {
                        vwCurrent = new Entities.ComplexType.VwLastValidatedValues();
                        vwCurrent.deferenced_value = "";
                    }
                    if (newValue[i].Value != vwCurrent.value)
                        
                        result.Add(new ModifiedValues
                        {
                            currentValue = newValue[i].DeferencedValue,
                            libele = newValue[i].FieldDisplayName,
                            oldValue = vwCurrent.deferenced_value,
                            Name = newValue[i].FieldName
                        });
                }
            }
            catch (Exception ex)
            {
                string ee = ex.Message;
                throw;
            }
            json = new JavaScriptSerializer().Serialize(result);

            return json;
        }

        [HttpPost]
        public string GetHistoriqueEntreprise(int entityId)
        {

            var allValues = _vwLastValidatedValuesService.GetLastValidatedValues(entityId);
            var intervallDate = (from a in allValues orderby a.validation_time descending select a.validation_time).Distinct().ToList();
            var tab = new Dictionary<Dictionary<int,int>,int>();
            List<HistoriqueEntreprise> modif = new List<HistoriqueEntreprise>();

            try
            {
                foreach (var dateTime in intervallDate)
                {
                    if (dateTime != null)
                    {
                        var oneDate = (DateTime) dateTime;

                        var year = oneDate.Year;
                        var mouth = oneDate.Month;
                        var day = oneDate.Day;

                        tab.Add(new Dictionary<int, int> {{year, mouth}}, day);
                    }
                }

                var distinctTabDayMounth = new Dictionary<Dictionary<int, int>, int>();
                foreach (var dic in tab)
                {
                    if (!distinctTabDayMounth.ContainsKey(dic.Key))
                    {
                        distinctTabDayMounth.Add(dic.Key, dic.Value);
                    }
                }

                var distinctTab = new Dictionary<Dictionary<int, int>, int>();
                foreach (var dic in distinctTabDayMounth)
                {
                    if (!distinctTab.ContainsKey(dic.Key) && !distinctTab.ContainsValue(dic.Value))
                    {
                        distinctTab.Add(dic.Key, dic.Value);
                    }
                }

                foreach (var intervalleDate in intervallDate)
                {
                    //int year = intervalleDate.Key.First().Key;
                    //int mounth = intervalleDate.Key.First().Value;
                    //int day = intervalleDate.Value;
                    if (intervalleDate != null)
                    {
                        DateTime dateToCompare = (DateTime) intervalleDate;
                        var valeur = (from a in allValues
                            where a.validation_time != null && (a.validation_time > dateToCompare &&
                                                                a.validation_time < dateToCompare.AddMilliseconds(1))

                            select a).ToList();
                        if (valeur.Count > 0)
                        {
                            modif.Add(new HistoriqueEntreprise {Modificatioins = valeur,DateModification = dateToCompare});
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                string zz = ex.Message;
                throw;
            }


            var json = new JavaScriptSerializer().Serialize(modif);
            return json;
        }


        [HttpPost]
        public string GenerateDateToWord(string dateToConvert)
        {
            var tab = dateToConvert.Split('/');
            var dt2 = DateTime.Parse(tab[2] + "-" + tab[1] + "-" + tab[0]);
            var dateConverted = ConvertDate.DateToText(dt2, false, false);

            if (dateConverted != null) return dateConverted;
            return "";
        }

        public ActionResult GetPdf(string code)
        {
            /*
            var unitOfWork = this.ControllerContext.GetUnitOfWork<BlogUnitOfWork>();
            var repository = unitOfWork.GetRepository<PostRepository>();
            var post = repository.GetByHashId(code);
            */
            var builder = new PdfBuilder(/* post, */Server.MapPath("/Views/Amp/Pdf.cshtml"));
            return builder.GetPdf();
        }


    }
}

Guce.MvcWebUI/Views/Form/Print.cshtml
@using Guce.Business.Abstract
@using Guce.Business.Concrete.Manager
@using Guce.DataAccess.Concrete
@model Guce.MvcWebUI.Models.Form.PrintListViewModel

@{
    ViewBag.Title = Model.Action.Name;
    ViewBag.Username = Session["username"];
    ViewBag.Groups = Session["userGroup"];
    Layout = "~/Views/Shared/_Layout.cshtml";
    IWorkflowService workflowService = new WorkflowManager(new EfWorkflowDal());
    IEntityService entityService = new EntityManager(new EfEntityDal());
    IVwCurrentValueService currentValueService = new VwCurrentValueManager(new EfVwCurrentValueDal(), new EfDicFieldDal());
    IDicCodeItemService codeService = new DicCodeItemManager(new EfDicCodeItemDal());
}

@section Javascript
{
<script type="text/javascript">
    var formPrintUrl = '@Url.Action("Print", "Form")';
    var findEntitieUrl = '@Url.Action("FindCurrentValueNotValidated", "Search")';
    var findNumeroDosierUrl = '@Url.Action("FindNumeroDossier", "Report")';
    var findInfoNotaire = '@Url.Action("FindInfoNotaire", "Report")';
    var GenerateDateToWord = '@Url.Action("GenerateDateToWord", "Report")';
    var drapeauUrl = '@Url.Content("~/Content/Images/drapeau_rdc.jpg")';
    var logoutUrl = '@Url.Action("Logout", "Login")';
    var fontUrl = '@Url.Content("~/fonts/ufonts.com_justify-regular-ttnorm.ttf")';
    var findMoreInfoNotaire = '@Url.Action("FindMoreInfoNotaire", "Report")';
    var FindFluxValues = '@Url.Action("FindFluxValues","Report")';
    var GetValueModified = '@Url.Action("GetValueModified","Report")';
    var GetHistoriqueEntreprise = '@Url.Action("GetHistoriqueEntreprise", "Report")';

    var fieldPropertiesUrl = '@Url.Action("GetFieldProperties", "Report")';

    var logoMo = '@Url.Content("~/Content/Images/logo_Mo.png")';
    var logoMoBis = '@Url.Content("~/Content/Images/logo_Mo_Bis.png")';
    var logoUrl = '@Url.Content("~/Content/Images/guce_print.jpg")';
    var logoBGUrl = '@Url.Content("~/Content/Images/guce_bg.jpg")';
    var p1Url = '@Url.Content("~/Content/Images/p1.JPG")';
    var checkUrl = '@Url.Content("~/Content/Images/sq2.jpg")';
    var uncheckUrl = '@Url.Content("~/Content/Images/sq.jpg")';
</script>
    
<script src="~/Scripts/Custom/HTMLPrintScript.js"></script>
    <script src="~/Scripts/Custom/formScript.js"></script>
<script src="~/Scripts/Custom/HTMLPrintGreffier.js"></script>
}
@* Store User's SessionId *@
<input type="hidden" id="sid" name="sid" value="@Session.SessionID"/>
<section class="content-header">
    @{
        var wflName = Model.VwUserNextAction != null ? Model.VwUserNextAction.WflName + " : "
            : workflowService.GetWorkflow(Model.WflId).Name + " : ";
        var entityName = Model.VwUserNextAction?.EntName != null ? "" + Model.VwUserNextAction.EntName
            : entityService.GetEntity(Model.EntityId).Name;
    }
    <h1>
        @wflName <small style="font-size: 16px;">@Model.Action.Name</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="~/Home"><i class="fa fa-home"></i>Accueil</a>
        </li>
        <li class="active">@Model.Action.Name</li>
    </ol>
</section>
<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@ViewBag.Title</h3>
                    <div class="box-tools pull-right">
                        <span class="label label-warning" style="margin-right: 20px;">@Model.Reference</span>
                        <span style="font-size: 13px;" class="label label-danger">@entityName</span>
                    </div>
                </div><!-- /.box-header -->
                <div class="form-horizontal">
                    <div class="box-body" style="background-color: lightgray;">
                        <input id="ActionId" type="hidden" name="ActionId" value="@Model.Action.Id" />
                        <input id="WflId" type="hidden" name="WflId" value="@Model.WflId" />
                        <input id="WfvId" type="hidden" name="WfvId" value="@Model.WfvId" />
                        <input id="FlowId" type="hidden" name="FlowId" value="@Model.FlowId" />
                        <input id="EntityId" type="hidden" name="EntityId" value="@Model.EntityId" />
                        <input id="StatusId" type="hidden" name="StatusId" value="@Model.StatusId" />
                        <input id="ReportId" type="hidden" name="ReportId" value="@Model.ReportId" />
                        <input id="FunctionToPrint" type="hidden" name="FunctionToPrint" value="@Model.FunctionToPrint" />
                        <!-- Content goes here -->

                        <div class="center-block" style="width: 700px; height: 100%; background-color: #FFFFFF;
                            padding: 35px; align-self: center;" id="textToPrint">
                            Chargement en cours . . .
                        </div>

                        @{
                            var objetSocial = currentValueService.GetCurrentValues(Model.EntityId).FindLast(v => v.FieldName.Equals("objetSocial"))?.Value;
                            var tab = objetSocial?.Split(' ');
                            if (tab != null && tab.Length > 70)
                            {
                                <div id="interCalaireObjetSocial" class="center-block" style="width: 700px; margin-top: 30px; height: 100%; background-color: #FFFFFF;padding: 35px; align-self: center;">
                                    Chargement en cours . . .
                                </div>
                            }
                            var testDirigeant = currentValueService.GetCurrentValues(Model.EntityId).Count(v => v.FieldName.Equals("dirigeant")) > 3;
                            var codeId = currentValueService.GetCurrentValues(Model.EntityId).FindLast(v => v.FieldName.Equals("formeJuridiqueN3")).CodeId;
                            if (codeId != null)
                            {
                                var formJuridiqueN3 = codeService.GetDicCodeItem((int)codeId).Code;
                                var testFormJuridiqueN3 = formJuridiqueN3.Equals("B11") || formJuridiqueN3.Equals("B10") || formJuridiqueN3.Equals("C10") || formJuridiqueN3.Equals("C10b");
                                var testAssocie = false;
                                if (testFormJuridiqueN3)
                                {
                                    testAssocie = currentValueService.GetCurrentValues(Model.EntityId).Count(v => v.FieldName.Equals("associe")) > 3;
                                }
                                if (testDirigeant || testAssocie)
                                {
                                    <div id="interCalaireEntity" class="center-block" style="width: 700px; margin-top: 30px; height: 100%; background-color: #FFFFFF;padding: 35px; align-self: center;">
                                        Chargement en cours . . .
                                    </div>
                                }
                            }
                            codeId = currentValueService.GetCurrentValues(Model.EntityId).FindLast(v => v.FieldName.Equals("formeJuridiqueN1")).CodeId;
                            if (codeId != null && codeService.GetDicCodeItem((int) codeId).Code.Equals("B"))
                            {
                                <div id="acteDepot" class="center-block" style="width: 700px; margin-top: 30px; height: 100%; background-color: #FFFFFF; padding: 35px; align-self: center;">
                                    Chargement en cours . . .
                                </div>
                            }
                        }

                        <div class="center-block" style="width: 700px; margin-top: 30px; height: 100%; background-color: #FFFFFF;
                                                                                                       padding: 35px; align-self: center;" id="textToPrint1">
                            Chargement en cours . . .
                        </div>

                        <div class="center-block" style="width: 700px; margin-top: 30px; height: 100%; background-color: #FFFFFF;
                        padding:35px; align-self: center;" id="textToPrint2">
                            
                        </div>

                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-left">
                            <a onclick='printReport("@Model.Action.Name");' id="pdf_button" class="btn btn-default">
                                <i class="fa fa fa-print text-red"></i> Imprimer
                            </a>
                        </div>
                        <div class="btn-group pull-right">
                            <button id="validateBtn" type="button" onclick="printEntreprise();" class="btn btn-info" style="margin-right: 5px;">
                                <i class="fa fa-check"></i> Valider
                            </button>
                            <a href="~/Home/" class="btn btn-default"><i class="fa fa-times"></i> Fermer</a>
                        </div>
                    </div><!-- /.box-footer -->
                </div>
            </div><!-- /.box -->
        </div>
    </div><!-- /.row -->
</section>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: "POST",
            url: fieldPropertiesUrl,
            success: function (response) {
                fieldPropertiesJson = $.parseJSON(response);
                loadReport();
            },
            error: function () {
                messageAlert("Erreur de chargement des libellés ...");
            }
        });
    });
</script>



   