Guce.MvcWebUI/Models/Stat/StatListViewModel.cs
using System.Collections.Generic;
using Guce.Entities.Concrete;

namespace Guce.MvcWebUI.Models.Stat
{
    public class StatListViewModel
    {
        public List<StatPage> StatPages { get; set; }
    }
}

Guce.MvcWebUI/Controllers/StatController.cs
/*=================================================================*
 * Classe: <StatController>
 * Version/date: <2.0.0> <2017.01.13>
 *
 * Description: <” Cette classe est le controleur pour la page des statsistiques. ”>
 * Specificities: <“ Cette classe est un controller. ”>
 *
 * Authors:  <Steve> <DILU>
 * Copyright: GUCE/ESSOR, all rights reserved
 *
 *================================================================*/

using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Guce.Business.Abstract;
using Guce.DataAccess.Concrete.Context;
using Guce.MvcWebUI.Models.Stat;
using Newtonsoft.Json;
using Npgsql;

namespace Guce.MvcWebUI.Controllers
{
    public class StatController : Controller
    {
        private readonly IStatPageService _statPageService;

        public StatController(IStatPageService statPageService)
        {
            _statPageService = statPageService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(new StatListViewModel
            {
                StatPages = _statPageService.GetStatPages()
            });
        }

        [HttpPost]
        public string ExecuteStat(int statId)
        {
            var stat = _statPageService.GetStatPage(statId);
            var query = stat.Request;
            var colNames = JsonConvert.DeserializeObject<List<string>>(stat.ColName);
            var values = new List<string>();
            using (var dbConnection = GuceContextConnexion.Initialize())
            {
                using (var connection = new NpgsqlConnection(dbConnection.ConnectionString))
                {
                    var command = new NpgsqlCommand(query, connection);
                    connection.Open();
                    var reader = command.ExecuteReader();
                    try
                    {
                        while (reader.Read())
                        {
                            values.AddRange(colNames.Select(col => reader[col].ToString()));
                        }
                    }
                    finally
                    {
                        reader.Close();
                    }
                }
            }
            return new JavaScriptSerializer().Serialize(colNames) + "=||=" + new JavaScriptSerializer().Serialize(values);
        }
    }
}

Guce.MvcWebUI/Views/Stat/Index.cshtml
@model Guce.MvcWebUI.Models.Stat.StatListViewModel

@{
    ViewBag.Title = "Statistiques";
    ViewBag.Username = Session["username"];
    ViewBag.Groups = Session["userGroup"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Javascript
{
    <script type="text/javascript">
        var executeStatUrl = '@Url.Action("ExecuteStat", "Stat")';
    </script>
    <script src="~/Scripts/Custom/statistiqueScript.js"></script>
    <script src="~/Scripts/Plugins/jquery.tabletoCSV.js"></script>
}

<section class="content-header">
    <h1>Statistiques</h1>
    <ol class="breadcrumb">
        <li>
            <a href="~/Home"><i class="fa fa-home"></i> Accueil</a>
        </li>
        <li class="active">Statistiques</li>
    </ol>
</section>
<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Statistiques</h3>
                    <div class="box-tools pull-right">
                        
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <div class="col-lg-12">
                            <div class="input-group" style="margin: 20px 50px;">
                                <select id="typeStat" class="form-control">
                                    @foreach (var stat in Model.StatPages)
                                    {
                                        <option value="@stat.Id">@stat.Name</option>
                                    }
                                </select>
                                <span class="input-group-btn">
                                    <button onclick="showStatistiques();" class="btn btn-primary" type="button">
                                        <i class="fa fa-search"></i> Rechercher
                                    </button>
                                </span>
                            </div><!-- /input-group -->
                            <div id="statResult">
                                
                            </div>
                        </div>
                    </div>
                    <!-- Content goes here -->
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <div class="pull-left">
                        <button id="exportCsvBtn" data-export="export" onclick="exportCsv();" class="btn btn-sm btn-success">
                            <i class="fa fa-download"></i> Exporter en CSV
                        </button>
                    </div>
                </div>
            </div><!-- /.box -->
        </div>
    </div><!-- /.row -->
</section>

<script type="text/javascript">
    $(document).ready(function () {
        $("#typeStat").prop("selectedIndex", -1);
        $("#exportCsvBtn").addClass("disabled");
    });
</script>